### ISSUE TITLE
After N-1 ingester crashes, query results are unstable

### ISSUE THREAD

**Issue by bboreham** [weaveworks/cortex#731]
We replicate to three ingesters but after losing two of them in an Unfortunate Incident, queries would sometimes contain results from just the two restarted instances which didn't have recent history.

It rights itself once those chunks age out of the remaining ingester into the store, but not great in the meantime.

**Comment by csmarchbanks** [comment]
This should be fixed by https://github.com/weaveworks/cortex/pull/732 correct?

**Comment by bboreham** [comment]
Different problem - #732 is about dropping samples on writes, while this is about reads from ingesters that have crashed and restarted.

**Comment by bboreham** [comment]
To improve the user experience, we could get the remaining ingesters to flush those chunks for which they hold the only remaining copy.

So, if I'm ingester X, and I know ingesters A and B have restarted, I iterate over all series in memory, run the distributor hash, and every series that maps to (A, B, X) I should flush.

How do I get to know A and B have restarted?  I guess that could be written as metadata into the ring, or we could just have a human type it in via an admin entrypoint.

Slight wrinkle: we will get the wrong hash for series with a blank label value, since we discard that information on entry to the ingester.

**Comment by bboreham** [comment]
How about:

We have ingesters remember the time their data starts, and hand that time over on a transfer.
If an ingester gets a query covering further back than that time, they return http status 206 - partial content.
Change the querier to not cancel remaining requests on 206.

**Comment by bboreham** [comment]
I think we can get into the same bad situation if you add a new ingester and then one old ingester restarts - there are now two places to get an incomplete answer.  And my suggestion at https://github.com/cortexproject/cortex/issues/731#issuecomment-435362741 helps there too.

**Comment by gouthamve** [comment]
Fixed by https://github.com/cortexproject/cortex/pull/1103

**Comment by gouthamve** [comment]
One possible fix is to use `shard-by-all-labels`, but even with that, if you're having 3 ingesters, and 2 ingesters go down and come back, we can ignore a (we only wait for 2 replys) different ingester in different queries, hence will have unstable queries.

**Comment by harry671003** [comment]
> Fixed by #1103

@gouthamve Was this issues fixed only for blocks store?

**Comment by bboreham** [comment]
The WAL can be used for chunks, but I think Goutham’s subsequent comment is saying it isn’t fixed.

**Comment by khaines** [comment]
Even the WAL can't prevent this 100% of the time because the WAL can only recover the samples a given ingester has received. While it is offline or otherwise not receiving data, nothing is being written to the WAL, while its replication partners are potentially receiving data.
