### ISSUE TITLE
Retry on errors from Dynamo

### ISSUE THREAD

**Issue by jml** [weaveworks/cortex#86]
When we attempt to write to dynamo, we will sometimes get errors. Currently, we abort on error.

This is almost never the right behaviour, because failing to write to dynamo (esp. during shut down) means loss of user data. Instead, we should retry.

Note that one major source of errors is being throttled by Dynamo. In this case, we should also retry, but we should be especially careful that we back off, lest we cause a cascading failure.

**Comment by jml** [comment]
@juliusv in  #84 points out that we do retry in normal operation but not during shutdown.

**Comment by jml** [comment]
Fixed by #119

**Comment by tomwilkie** [comment]
Still not doing retries on shutdown

**Comment by jml** [comment]
Ah right. Kind of curious now as to what @juliusv meant when he said we were backing off already.

**Comment by tomwilkie** [comment]
retry, not backoff.

its because we don't drop the chunks if we fail to persist them, so they'll get retried on a later pass.

**Comment by tomwilkie** [comment]
https://github.com/weaveworks/cortex/pull/153 makes us retry and throttling for dynamodb, even on flush.

We still don't retry other errors, but we haven't observed any yet.
